const config = {
  encoding: "UTF-8",
  max_number: 10,
  showMessage: true,
  auto_sort: false,
  timeFormat: "%Y-%m-%d",
  reverse: false,
  divide_by: "type",
  divide_color_by: "name",
  color: {
    "Singularity0909": "#00CCFF"
  },
  changeable_color: false,
  divide_changeable_color_by_type: true,
  color_range: ["#ff7e5f", "#feb47b"],
  itemLabel: "🏆",
  typeLabel: "COMBO",
  item_x: 250,
  interval_time: 1,
  text_y: -50,
  text_x: 1000,
  offset: 350,
  display_barInfo: 0,
  use_counter: true,
  step: 1,
  format: ".0f",
  postfix: "",
  deformat: function(val, postfix) {
    return Number(val.replace(postfix, "").replace(/\,/g, ""));
  },
  left_margin: 250,
  right_margin: 150,
  top_margin: 180,
  bottom_margin: 0,
  dateLabel_switch: true,
  dateLabel_x: null,
  dateLabel_y: null,
  allow_up: false,
  always_up: false,
  enter_from_0: true,
  big_value: true,
  use_semilogarithmic_coordinate: false,
  long: false,
  wait: 0,
  update_rate: 1,
  // animation: 'linear',
  showLabel: true,
  labelx: -10,
  use_img: false,
  imgs: {

  },
  background_color: "#FFFFFF",
  rounded_rectangle: true,
  show_x_tick: true,
  bar_name_max: 30
};